### ISSUE TITLE
Criação do RestController para listar cliente no EndPoint do serviço ClienteService

### ISSUE THREAD

**Issue by Bruunaa** [Bruunaa/helpr-1#3]
[ ] Criar um controlador Rest
[ ] Criar o serviço de cliente
[ ] Criar métodos para o endpoint de RestController
[ ] Vincular os repositórios de cliente
[ ] Executar testes no postman

**Comment by soulcode-acad** [comment]
Bruna trabalho show como sempre alguns detalhes precisam ser colocados: Faltou etiquetar e assinar as tarefas e entregas para ajudar o revisor mas é detalhe. Porém código estava limpo e bem feito e teve algumas linhas que precisariam de mais ordem para futuras implementações.
![image](https://user-images.githubusercontent.com/100297907/172867234-cb3fb6c8-7914-4413-81a9-72a8f74eca28.png)
